
[build]
  command = "npm run build"
  publish = ".next"
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "false" }

# Netlify functions configuration
[functions]
  directory = "netlify/functions"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
